### ISSUE TITLE
Retrieving MAC Address of the device

### ISSUE THREAD

**Issue by abbasidaniyal** [once10301/wifi#15]
I will be working, inorder to add the option to retrieve the WiFi MAC address of the device

**Comment by MichaelDark** [comment]
@abbasidaniyal What about a progress on this issue? Are you imlementing it right now or I should find another solution?

**Comment by abbasidaniyal** [comment]
Apologies but since Android 6 onwards, it's become almost impossible to retrieve the MAC address. 
If you can find another solution, that'll be great!
