### ISSUE TITLE
Cannot list down Wifi ssid(s).

### ISSUE THREAD

**Issue by Ramiiyan** [once10301/wifi#24]
I tried to list down available wifi list, it's not working. and when I tried with debug console i didn't get any errors. 
loadData() is not working.
void loadData() async {
    await Wifi.list('').then((list) {
      setState(() {
        ssidList = list;
      });
    });
  }

**Comment by ghost** [comment]
If you want a specific list of wifi devices follow as shown below:

```
//Declare the list
List<WifiResult> ssidList = [];
List wifilist=new List();

_wifiList()async{
    Wifi.list('').then((list) {
      setState(() {
        ssidList = list.toSet().toList();
        for (var i = 0; i < ssidList.length; i++) {
          wifiList.add(ssidList[i].ssid.toString());
        }
      });
    });
}

```

**Comment by Ramiiyan** [comment]
> If you want a specific list of wifi devices follow as shown below:
> 
> ```
> //Declare the list
> List<WifiResult> ssidList = [];
> List wifilist=new List();
> 
> _wifiList()async{
>     Wifi.list('').then((list) {
>       setState(() {
>         ssidList = list.toSet().toList();
>         for (var i = 0; i < ssidList.length; i++) {
>           wifiList.add(ssidList[i].ssid.toString());
>         }
>       });
>     });
> }
> ```
thanks, it's worked.

**Comment by DhavalRKansara** [comment]
> > If you want a specific list of wifi devices follow as shown below:
> > ```
> > //Declare the list
> > List<WifiResult> ssidList = [];
> > List wifilist=new List();
> > 
> > _wifiList()async{
> >     Wifi.list('').then((list) {
> >       setState(() {
> >         ssidList = list.toSet().toList();
> >         for (var i = 0; i < ssidList.length; i++) {
> >           wifiList.add(ssidList[i].ssid.toString());
> >         }
> >       });
> >     });
> > }
> > ```
> 
> thanks, it's worked.

I tried the same still I am getting an empty list.

Actually I am working on an IOT project in which I have to connect my IOT device to any Wifi and that's why I need a list of all available wifi list with SSID.

**Comment by Ramiiyan** [comment]
@DhavalRKansara You need to turn on the GPS location, then it will show wifi list. it's an access problem with android.

**Comment by DhavalRKansara** [comment]
> @DhavalRKansara You need to turn on the GPS location, then it will show wifi list. it's an access problem with android.

My GPS location is already turn on still m not getting an empty list.

**Comment by Ramiiyan** [comment]
> My GPS location is already turn on still m not getting an empty list.

can you post your code? wifi list part?

**Comment by DhavalRKansara** [comment]
@Ramiiyan  Okay, There were some minor mistakes from my side for calling function `_wifiList`.  Now I am getting all the available wifi list.

Now, I am working on one IOT project so I have one more requirement which is I need a parameter that each wifi network from that list is secure or not. Is there any solution for these?

**Comment by Ramiiyan** [comment]
@DhavalRKansara  from my knowledge getting secure details is not available at this moment, 
But, You can try this, (**NOT An Optimized Way**)
connect each wifi SSID with an empty Password. if it's Allow to Connect then it's **not Secured** else **Secured**.

**Comment by DhavalRKansara** [comment]
> @DhavalRKansara from my knowledge getting secure details is not available at this moment,
> But, You can try this, (**NOT An Optimized Way**)
> connect each wifi SSID with an empty Password. if it's Allow to Connect then it's **not Secured** else **Secured**.

I don't think so this is a proper solution because while showing that list to the user for establishing the connection I have to show them that password is required for that network or not.

I already raised and separate [issue](https://github.com/once10301/wifi/issues/35) for the same.
