### ISSUE TITLE
registerWith gives NPE when using Flutter's background execution on Android

### ISSUE THREAD

**Issue by ryanheise** [once10301/wifi#4]
Flutter's new background execution feature (described here: https://medium.com/flutter-io/executing-dart-in-the-background-with-flutter-plugins-and-geofencing-2b3e40a1a124) allows plugins to be registered in a background context (e.g. a Service). The problem is that the wifi plugin assumes that the context for plugin registration is an activity with this line of code:

`		WifiManager wifiManager = (WifiManager) registrar.activity().getApplicationContext().getSystemService(Context.WIFI_SERVICE);`

`registrar.activity()` may now return null, and this leads to a NPE:

```
E/AndroidRuntime( 2453): 	at com.ly.wifi.WifiPlugin.registerWith(WifiPlugin.java:23)
E/AndroidRuntime( 2453): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:30)
```

The solution is to change the above line of code to this:

`		WifiManager wifiManager = (WifiManager) registrar.activeContext().getApplicationContext().getSystemService(Context.WIFI_SERVICE);`

**Comment by wheel1992** [comment]
@ryanheise will you do a pull request for this change?

**Comment by marcolettieri** [comment]
for the same reason if activity is opened and service background is started IntentReceiverLeaked is raised:
`has leaked IntentReceiver com.ly.wifi.WifiDelegate$NetworkChangeReceiver@7b14e1c that was originally registered here. Are you missing a call to unregisterReceiver()?`
add unregister receiver before the register:
```java
try{
  registrar.context().unregisterReceiver(delegate.networkReceiver);
}catch(Exception ignored){}
try{
  registrar.context().registerReceiver(delegate.networkReceiver, filter);
}catch(Exception ignored){}
```

or follow this:https://stackoverflow.com/questions/2682043/how-to-check-if-receiver-is-registered-in-android
