### ISSUE TITLE
exception on Wifi.list()

### ISSUE THREAD

**Issue by carterw** [once10301/wifi#5]
Trying to invoke some methods in this package and getting an exception on Wifi.list().

It calls this function;
`  static Future<T> list<T>(String key) async {
    final Map<String, dynamic> params = {
      'key': key,
    };
    return await _channel.invokeMethod('list', params);
  }`

...and an uncaught exception is thrown;
type 'List<dynamic>' is not a subtype of type 'FutureOr<List<String>>'

**Comment by once10301** [comment]
I do not understand what you mean

**Comment by carterw** [comment]
When I call the Wifi.list() method an exception is thrown as shown above. Am I doing something wrong?

**Comment by once10301** [comment]
Are you calling on an Android device? Or an iOS device?

**Comment by carterw** [comment]
On an Android device.

**Comment by once10301** [comment]
I joined the signal strength function yesterday. Can you try again with the latest one and send me the error log?

**Comment by carterw** [comment]
I just ran it and saw the error, how do I extract the error log?

This is your example for listing access points;
`  List<String> ssidList = await Wifi.list('key'); // this key is used to filter`


But in the editor that method call is underlined in red with this pop-up;
`A value of type 'List<WifiResult>' can't be assigned to a variable of type 'List<String>'.`

So I change that line like so, which runs without error;
`List<WifiResult> ssidList = await Wifi.list('key'); // this key is used to filter`

... but the ssidList is empty. How should I call it if I want to see all SSID's without filtering?

**Comment by carterw** [comment]
Okay I think I see how - instead of 'key' I used the null string '' and get back a list of WiFiResult objects.

I suggest that you correct the example code in the Readme and document the WiFiResult.

**Comment by once10301** [comment]
Sorry, this is my negligence. I only got ssid before, so it is String, I have modified and submitted it.

**Comment by Ramiiyan** [comment]
> Okay I think I see how - instead of 'key' I used the null string '' and get back a list of WiFiResult objects.
> 
> I suggest that you correct the example code in the Readme and document the WiFiResult.

I tried this part to get the ssid list, but even I don't get an empty list. can you help me to get the wifiResult??
