### ISSUE TITLE
Wifi.connection() returns success with bad arguments

### ISSUE THREAD

**Issue by carterw** [once10301/wifi#7]
I tried just the raw example which presumably should have failed;
```
var result = await Wifi.connection('ssid', 'password');
print(result);
```
The result was "WifiState.success".  I had already been connected to a WiFi access point prior to the connection attempt. Are you reporting the result of the connect attempt or merely the current state?

**Comment by once10301** [comment]
This feature is not recommended if it is not necessary. I can't guarantee that the connection will be successful every time. If this wifi has already remembered the password, not connected.
